### ISSUE TITLE
레이블 생성

### ISSUE THREAD

**Issue by zzawang** [codesquad-masters2024-team02/issue-tracker#2]
## ✏️ 기능 설명
레이블을 생성한다.

<br><br>

## ✅ TODO
- [x] 이름, 배경 색깔 공백 검사
- [x] 배경 색깔 유효성 검사
- [x] DB에 저장
- [x] 구현한 기능 Test

<br><br>

## 📕 참고할만한 자료(선택)
https://spring.io/projects/spring-data-jdbc
