### ISSUE TITLE
메인 이슈 리스트

### ISSUE THREAD

**Issue by minjeongHEO** [codesquad-masters2024-team02/issue-tracker#28]
## ✅ TODO
🚧 API 연동 전

✨레이아웃
- [x] Headr부분 레이아웃
  - [x] 로고 
  - [x] 유저 이미지
- [x] Main 부분 레이아웃
- [x] 리스트 상단 필터링 드롭다운 
    - [x] 체크 박스 
    - [x] 열린 이슈 / 닫힌 이슈 
    - [x] 담당자 / 레이블 / 마일 스톤 / 작성자 필터 드롭다운
- [x] 상단 필터  input
- [x] 상단 레이블 버튼
- [x] 상단 마일 스톤 버튼
- [x] 상단 이슈 작성 버튼
- [x] 현재의 검색 필터 및 정렬 지우기 레이아웃
- [x] 리스트 - 라벨 개수 제한없는 레이아웃
- [x] 리스트 - 담당자 개수 제한없는 레이아웃
- [ ] 리스트 -  "검색과 일치하는 결과가 없습니다"

🛠 기능
- [x] 리스트 상단 필터링 드롭다운 체크 상태 관리(Reducer)
- [x] 필터 선택 시 input값에 value추가
- [x] 필터 선택 시 클리어(현재의 검색 필터 및 정렬 지우기) 기능
- [x] 전체 체크 박스 클릭
  - [x] 리스트 체크 박스 전체 클릭 됨
  - [x] nav 바뀜
  - [x] 전체 체크 박스 개수 count
- [x] 전체 체크 박스 클릭 해지 시
  - [x] 리스트 체크 박스 전체 클릭 해지 됨
  - [x] nav 다시 바뀜
- [x] 리스트 체크 박스 클릭 시
  - [x] nav 바뀜
  - [x] 체크 박스 개수 count
- [ ] 리스트 체크 박스 클릭 시
- [ ] 리스트 검색 결과 없을 시 "검색과 일치하는 결과가 없습니다" 리스팅

<br><br>
## ✏️ 기능 설명

<br><br>
