### ISSUE TITLE
[Sprint1] BE 리뷰받은 사항 적용

### ISSUE THREAD

**Issue by zzawang** [codesquad-masters2024-team02/issue-tracker#29]
## ✏️ 기능 설명
Sprint1에서 BE 리뷰어로부터 리뷰받은 사항을 적용한다.

<br><br>

## ✅ TODO
- [x] 메소드 이름으로 의미가 잘 들어난다면 굳이 주석쓰지 않기
- [x] 예외가 왜 발생했는지 로깅하기
- [x] 호출 될 때마다 Random 인스턴스를 생성하는 부분 수정하기
- [x] @Transactional 적용
- [x] DTO setter 없애기
- [x] getMember ➡️ toMemebr or toMemebrDto로 변경

<br><br>
