### ISSUE TITLE
라벨 리스트, 개수

### ISSUE THREAD

**Issue by zzawang** [codesquad-masters2024-team02/issue-tracker#32]
## ✏️ 기능 설명
라벨 목록과 라벨의 개수를 전송하는 API를 구현한다.

<br><br>

## ✅ TODO
- [x] 라벨 배경 색 랜덤 생성 URI 수정
- [x] 라벨 배경 색 DTO로 반환
- [x] 라벨 목록 API 구현
- [x] 라벨 개수 API 구현

<br><br>
