### ISSUE TITLE
파일 저장 및 조회

### ISSUE THREAD

**Issue by parksangchu** [codesquad-masters2024-team02/issue-tracker#38]
## ✏️ 기능 설명
이슈 및 코멘트 저장, 조회에서 사용할 파일 서비스를 S3와 연동하여 구현한다.

## ✅ TODO
- [x] 프로젝트와 S3를 연동할 수 있다.
- [x] 파일을 S3 및 데이터베이스에 저장할 수 있다.
- [x] 파일을 S3 및 데이터베이스에서 가져올 수 있다.
- [x] 파일을 S3 및 데이터베이스에서 삭제할 수 있다.
