### ISSUE TITLE
이슈 필터

### ISSUE THREAD

**Issue by zzawang** [codesquad-masters2024-team02/issue-tracker#43]
## ✏️ 기능 설명
사용자가 요청한 필터 조건에 따라 필터링된 이슈 목록들을 반환한다.

<br><br>

## ✅ TODO
- [x] 필터 조건에 따른 동적 쿼리 생성
- [x] Repository마다 필요한 Read문 생성
- [x] 필터링된 이슈 리스트 반환
- [x] 열린/닫힌 이슈의 개수 반환

<br><br>

## 📕 참고할만한 자료(선택)
https://github.com/spring-projects/spring-data-relational/blob/main/spring-data-jdbc/src/main/java/org/springframework/data/jdbc/core/mapping/AggregateReference.java

https://github.com/benelog/entity-dev/blob/master/src/index.adoc
