### ISSUE TITLE
이슈 상세

### ISSUE THREAD

**Issue by parksangchu** [codesquad-masters2024-team02/issue-tracker#46]
## ✏️ 기능 설명
이슈 상세 내용을 조회할 수 있다.
<br><br>

## ✅ TODO
- [x] 이슈의 본문을 가져온다.
- [x] 이슈에 첨부된 파일을 가져온다.
- [x] 이슈의 담당자, 라벨, 마일스톤을 가져온다.
- [x] 이슈의 코멘트를 가져온다.

<br><br>
