### ISSUE TITLE
이슈 필터링 구조 변경

### ISSUE THREAD

**Issue by zzawang** [codesquad-masters2024-team02/issue-tracker#48]
## ✏️ 기능 설명
이슈 필터링 조건을 받는 쿼리 파라미터들을 변경함에 따라 구조를 변경한다.

<br><br>

## ✅ TODO
- [x] 필터링 DTO 라벨 아이디 -> 이름으로 변경
- [x] 필터링 DTO 마일스톤 아이디 -> 이름으로 변경
- [x] 필터링 DTO에 작성자, 라벨, 마일스톤이 없는 조건을 체크할 필드 추가
- [x] 담당자 Id 리스트 -> SimpleMemberDto(아이디 & 파일 url)리스트로 변경(Fileservice의 `getImgUrlById()` 사용)

<br><br>
