### ISSUE TITLE
CI/CD 구축

### ISSUE THREAD

**Issue by zzawang** [codesquad-masters2024-team02/issue-tracker#60]
## ✏️ 기능 설명
프로젝트를 자동 배포하기 위해 CI/CD 파이프라인을 구축한다.

<br><br>

## ✅ TODO
- [x] 테스트 실행하는 CI 구축
- [x] Github Actions를 사용하여 Jar파일 빌드
- [x] dockerfile을 통해 이미지를 빌드 & docker repo로 push 
- [x] Ec2 Ubuntu 서버에 접속 후 Docker 이미지 가져와서 배포

<br><br>

## 📕 참고할만한 자료(선택)
https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
https://docs.docker.com/build/ci/github-actions/
