### ISSUE TITLE
코드 리팩토링

### ISSUE THREAD

**Issue by zzawang** [codesquad-masters2024-team02/issue-tracker#69]
## ✏️ 기능 설명
전반적인 구조와 코드를 리팩토링한다.

<br><br>

## ✅ TODO
- [ ] 접근 수준을 갖는 생성자로 롬복 수정하기 (Ex) `@allargsconstructor(access = accesslevel.private)`)
- [ ] immutable한 값을 반환하도록 변경하기
- [ ] @CreatedDate, @LastModifiedDate 적용
- [ ] LoginService 코드 분리

<br><br>
